enum actionKeys {

    // Project action keys
    LOAD_PROJECTS = 'LOAD_PROJECTS',
    ADD_PROJECT = 'ADD_PROJECT',
    EDIT_PROJECT = 'EDIT_PROJECT',
    UPDATE_PROJECT = 'UPDATE_PROJECT',
    DELETE_PROJECT = 'DELETE_PROJECT',
    LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS',
    ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS',
    EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS',
    UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
    DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS',
    SHOW_CREATE_PROJECT_DIALOG = 'SHOW_CREATE_PROJECT_DIALOG',
    HIDE_CREATE_PROJECT_DIALOG = 'HIDE_CREATE_PROJECT_DIALOG'
}

export default actionKeys;