enum actionKeys {

  // Project action keys
  EDIT_PROJECT = 'EDIT_PROJECT',
  LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS',
  ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS',
  UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS',
  DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS',

  // TimeLog action keys
  EDIT_TIMELOG = 'EDIT_TIMELOG',
  LOAD_TIMELOGS_SUCCESS = 'LOAD_TIMELOGS_SUCCESS',
  ADD_TIMELOG_SUCCESS = 'ADD_TIMELOG_SUCCESS',
  SAVE_TIMELOG_SUCCESS = 'SAVE_TIMELOG_SUCCESS',
  DELETE_TIMELOG_SUCCESS = 'DELETE_TIMELOG_SUCCESS',

  // Timer action keys
  START_TIMER_SUCCESS = 'START_TIMER_SUCCESS',
  STOP_TIMER_SUCCESS = 'STOP_TIMER_SUCCESS',
  LOAD_TIMER_SUCCESS = 'LOAD_TIMER_SUCCESS',
  HANDLE_TIMER_CHANGE = 'HANDLE_TIMER_CHANGE'
}

export default actionKeys;